# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      - image: circleci/clojure:tools-deps-1.10.1.739

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-
      - run: clojure -P -M:test:runner:jar:deploy
      - save_cache:
          paths:
            - ~/.m2
          key: v4-dependencies-{{ checksum "deps.edn" }}

  test:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:tools-deps-1.10.1.739
      - image: confluentinc/cp-zookeeper:5.3.1
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
      - image: confluentinc/cp-kafka:5.3.1
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      - image: confluentinc/cp-schema-registry:5.3.1
        environment:
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:2181
          SCHEMA_REGISTRY_HOST_NAME: localhost
          SCHEMA_REGISTRY_LISTENERS: http://localhost:8081
      - image: confluentinc/cp-kafka-rest:5.3.1
        environment:
          KAFKA_REST_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_REST_LISTENERS: http://0.0.0.0:8082
          KAFKA_REST_SCHEMA_REGISTRY: http://localhost:8081
          KAFKA_REST_HOST_NAME: localhost

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-

      # run tests!
      - run: clojure -M:test:runner --reporter kaocha.report/documentation

      - store_test_results:
          path: test-results

      - store_artifacts:
          path: logs

  deploy:
    docker:
      - image: circleci/clojure:tools-deps-1.10.1.739

    working_directory: ~/repo

    environment:
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v4-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v4-dependencies-

      - run: clojure -X:depstar jar :sync-pom true :group-id cddr :artifact-id test-machine :version $CIRCLE_TAG :jar test-machine.jar
      - run: clojure -M:deploy

workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          filters:
            branches:
              only: /main/
            tags:
              only: /^v.*/
          requires:
            - test
          context: clojars-deploy
