# Clojure CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-clojure/ for more details
#
version: 2.1
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/clojure:tools-deps-1.10.1.739
      - image: confluentinc/cp-zookeeper:5.3.1
        environment:
          ZOOKEEPER_CLIENT_PORT: 2181
      - image: confluentinc/cp-kafka:5.3.1
        environment:
          KAFKA_BROKER_ID: 1
          KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
          KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
          KAFKA_ZOOKEEPER_CONNECT: localhost:2181
      - image: confluentinc/cp-schema-registry:5.3.1
        environment:
          SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: localhost:2181
          SCHEMA_REGISTRY_HOST_NAME: localhost
          SCHEMA_REGISTRY_LISTENERS: http://localhost:8081
      - image: confluentinc/cp-kafka-rest:5.3.1
        environment:
          KAFKA_REST_ZOOKEEPER_CONNECT: localhost:2181
          KAFKA_REST_LISTENERS: http://0.0.0.0:8082
          KAFKA_REST_SCHEMA_REGISTRY: http://localhost:8081
          KAFKA_REST_HOST_NAME: localhost

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v3-dependencies-{{ checksum "deps.edn" }}
            # fallback to using the latest cache if no exact match is found
            - v3-dependencies-

      - run: clojure -P -M:runner

      - save_cache:
          paths:
            - ~/.m2
          key: v3-dependencies-{{ checksum "deps.edn" }}

      # run tests!
      - run: clojure -M:runner
